### ISSUE TITLE
Change repo topics

### ISSUE THREAD

**Issue by jf990** [Esri/mapbook-ios#56]
To be consistent with other Esri repo topics categorization, please remove topics `ios-swift` and `ios-app`, add topics `native-development`, `ios`, and `swift`

**Comment by esreli** [comment]
I've requested for ownership from github_admin of this repo so that I can change the tags.

**Comment by esreli** [comment]
I've been granted ownership.

The topics should now be consistent with what is outlined above.

**Comment by jf990** [comment]
looks good, thanks!

https://github.com/Esri?q=topic:swift
