### ISSUE TITLE
Remove ATS allows arbitrary loads. 

### ISSUE THREAD

**Issue by esreli** [Esri/mapbook-ios#63]
ArcGIS Online has updated it's owning system URL. https://www.arcgis.com/sharing/rest/info?f=pjson

This change should be reflected in

- [x] XCode
~README~

**Comment by esreli** [comment]
@mikewilburn this change has been implemented. Would you test to confirm it has been implemented successfully?

You can confirm this change has been implemented properly if you are able to authenticate with AGOL.

**Comment by mikewilburn** [comment]
Confirmed this works by signing into https://www.arcgis.com, https://runtime.maps.arcgis.com, or https://arcgisruntime.maps.arcgis.com.
