### ISSUE TITLE
Update the default portal url string to omit the 'www'

### ISSUE THREAD

**Issue by mikewilburn** [Esri/mapbook-ios#73]
Logging into the generic `https://www.arcgis.com` portal works just fine.
However, modifying the string to be that of a specific portal, say `https://www.runtime.maps.arcgis.com`, will throw an error:

> An SSL error has occurred and a secure connection to the server cannot be made.

This is because the 'www' ought to be omitted in this case --> `https://runtime.maps.arcgis.com` should be used instead.
To encourage this, and to prevent users from running into this error, I suggest we remove the `www` from the default string altogether.

**Comment by esreli** [comment]
@mikewilburn your requested change has been merged into `master`. Would you confirm?

**Comment by mikewilburn** [comment]
Just checked out the change and it LGTM.

![image](https://user-images.githubusercontent.com/25207711/47822526-ae232c00-dd21-11e8-84ca-6441bb279e47.png)
