### ISSUE TITLE
Consider deleting the v.next branch

### ISSUE THREAD

**Issue by stevebaranski** [Esri/mapbook-ios#85]
At the time of this writing, `v.next` is 14 commits behind `master`, and [recent PRs](https://github.com/Esri/mapbook-ios/pulls?utf8=✓&q=is%3Apr) have been initiated directly from feature branches. This is perfectly reasonable, given the maturity of this sample project. 

Are there downstream implications to this change (e.g., branch protection, CI jobs, etc.) to consider before resolving this issue?

**Comment by esreli** [comment]
There are no downstream implications to this change. `v.next` has gone stale since the release of Mapbook 1.1.

**Comment by esreli** [comment]
`v.next` is deleted, closing this issue.
